[package]
name = "llm"
version = "1.0.4"
edition = "2021"
description = "A Rust library unifying multiple LLM backends."
license = "MIT"
authors = ["Tristan Granier <graniet75@gmail.com>"]
repository = "https://github.com/graniet/llm"
documentation = "https://docs.rs/llm"
homepage = "https://github.com/graniet/llm"

[features]
default = []
openai = []
anthropic = []
ollama = []
deepseek = []
xai = []
phind = []
google = []
groq = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.12", features = ["json"] }
serde_json = "1.0"
async-trait = "0.1"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
